apiVersion: apps/v1
kind: Deployment
metadata:
  name: renovate
  labels:
    app: renovate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: renovate
  template:
    metadata:
      labels:
        app: renovate
    spec:
      containers:
      - name: renovate
        image: renovate/renovate:latest
        args: ["--autodiscover"]
        env:
        - name: RENOVATE_TOKEN
          valueFrom:
            secretKeyRef:
              name: renovate-secret
              key: RENOVATE_TOKEN
        volumeMounts:
        - name: config-volume
          mountPath: /usr/src/app/renovate.json
          subPath: renovate.json
      volumes:
      - name: config-volume
        configMap:
          name: renovate-config
